Refactor/add compensatory rollback
FIAP-SOAT-G19/payments-microsservice pull request #13
Opened 2024-07-06 21:08 UTC by vanessalimaf

Adicionando ações compensatórias

2024-07-08 11:53 UTC, rodrigodos-santos approved these changes

2024-07-14 15:41 UTC, me-marchi requested changes

2024-07-14 15:41 UTC, me-marchi commented on k8s/api-payments-deployment.yaml
> +
acho que esta faltando o cancel-order-queue aqui

2024-07-14 16:50 UTC, me-marchi approved these changes

2024-07-14 17:27 UTC, merged